# Generated by Django 2.2.5 on 2020-07-15 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('art_id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200)),
                ('designation', models.CharField(db_index=True, max_length=255, null=True)),
                ('code', models.CharField(db_index=True, max_length=100, null=True)),
                ('ref', models.CharField(db_index=True, max_length=255, null=True)),
                ('umesure', models.CharField(max_length=50, null=True)),
                ('emp', models.CharField(max_length=50, null=True)),
                ('qte', models.PositiveIntegerField(null=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='magasin.Category')),
            ],
            options={
                'ordering': ('code', 'designation'),
            },
        ),
    ]
