# Generated by Django 2.0.5 on 2020-08-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_magasinlog_movement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magasinlog',
            options={'ordering': ('log_date', 'art_id')},
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='code',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='qte',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='umesure',
        ),
        migrations.RemoveField(
            model_name='magasinlog',
            name='valeur',
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='qte',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='magasinlog',
            name='art_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='magasin.Article'),
        ),
    ]
