# Generated by Django 2.2.5 on 2020-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_auto_20200831_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasinlog',
            name='operation',
            field=models.CharField(max_length=30),
        ),
    ]
