# Generated by Django 2.2.5 on 2020-08-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_auto_20200831_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasinlog',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magasinlog',
            name='designation',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magasinlog',
            name='emp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='magasinlog',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='magasinlog',
            name='umesure',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
