# Generated by Django 2.2.5 on 2020-08-31 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_auto_20200831_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mov_user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
