# Generated by Django 2.2.5 on 2020-09-15 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0009_auto_20200831_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionStocks',
            fields=[
                ('gs_id', models.AutoField(primary_key=True, serialize=False)),
                ('gs_date', models.DateTimeField()),
                ('ent_qte', models.PositiveIntegerField(null=True)),
                ('ent_prix', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ent_valeur', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('srt_qte', models.PositiveIntegerField(null=True)),
                ('srt_prix', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('srt_valeur', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('sf_qte', models.PositiveIntegerField(null=True)),
                ('sf_prix', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('sf_valeur', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_art_id', to='magasin.Article')),
            ],
            options={
                'ordering': ('gs_date', 'gs_id', 'art_id'),
            },
        ),
    ]
