# Generated by Django 2.0.5 on 2020-09-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_gestionstocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='observation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
