# Generated by Django 2.0.5 on 2021-05-22 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magasin', '0012_auto_20210518_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_date', models.DateTimeField()),
                ('qte', models.PositiveIntegerField(null=True)),
                ('art_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_art_id', to='magasin.Article')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
