# Generated by Django 2.2.5 on 2020-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('fourrnis_id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255, null=True)),
                ('code_postal', models.IntegerField(null=True)),
                ('wilaya', models.CharField(max_length=255, null=True)),
                ('pays', models.CharField(max_length=255)),
                ('telephone', models.IntegerField()),
                ('fax', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('note', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('fourrnis_id', 'nom'),
            },
        ),
    ]
