# Generated by Django 2.2.5 on 2020-08-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='wilaya',
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='code_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, default='null', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='fax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='pays',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
