# Generated by Django 2.0.5 on 2020-08-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0003_auto_20200828_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='fourniture',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
