# Generated by Django 2.0.5 on 2021-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0004_fournisseur_fourniture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='nom',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
