# Generated by Django 4.0 on 2025-04-25 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0005_auto_20210522_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
