# Generated by Django 4.0 on 2025-04-25 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseur', '0006_fournisseur_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ('-created', 'nom')},
        ),
    ]
